//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesServiceHost.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISaleService")]
    public interface ISaleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleService/InsertCustomer", ReplyAction="http://tempuri.org/ISaleService/InsertCustomerResponse")]
        bool InsertCustomer(SaleClassLibrary.Customer obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleService/GetAllCustomer", ReplyAction="http://tempuri.org/ISaleService/GetAllCustomerResponse")]
        SaleClassLibrary.Customer[] GetAllCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleService/DeleteCustomer", ReplyAction="http://tempuri.org/ISaleService/DeleteCustomerResponse")]
        bool DeleteCustomer(int cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleService/UpdateCustomer", ReplyAction="http://tempuri.org/ISaleService/UpdateCustomerResponse")]
        bool UpdateCustomer(SaleClassLibrary.Customer obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaleService/GetRottenTomatoesMovieInfo", ReplyAction="http://tempuri.org/ISaleService/GetRottenTomatoesMovieInfoResponse")]
        string GetRottenTomatoesMovieInfo(string queryString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISaleServiceChannel : SalesServiceHost.ServiceReference1.ISaleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaleServiceClient : System.ServiceModel.ClientBase<SalesServiceHost.ServiceReference1.ISaleService>, SalesServiceHost.ServiceReference1.ISaleService {
        
        public SaleServiceClient() {
        }
        
        public SaleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertCustomer(SaleClassLibrary.Customer obj) {
            return base.Channel.InsertCustomer(obj);
        }
        
        public SaleClassLibrary.Customer[] GetAllCustomer() {
            return base.Channel.GetAllCustomer();
        }
        
        public bool DeleteCustomer(int cid) {
            return base.Channel.DeleteCustomer(cid);
        }
        
        public bool UpdateCustomer(SaleClassLibrary.Customer obj) {
            return base.Channel.UpdateCustomer(obj);
        }
        
        public string GetRottenTomatoesMovieInfo(string queryString) {
            return base.Channel.GetRottenTomatoesMovieInfo(queryString);
        }
    }
}
